### ISSUE TITLE
Replace rusty-result-ts with neverthrow

### ISSUE THREAD

**Issue by Xkonti** [Xkonti/quasar-clean-typescript#11]
The `rusty-result-ts` package has been archived. Use the [neverthrow package](https://github.com/supermacro/neverthrow) instead.

**Comment by corners2wall** [comment]
Hello, I wanna try this. Assign to me please

**Comment by Xkonti** [comment]
@corners2wall It's all yours! Let me know if you have any issues and I'll be happy to help.

**Comment by corners2wall** [comment]
@Xkonti after research I have a problem with compare types in `axios-service-base-ts` package. Needed fix there and then here.  Assign [this](https://github.com/Xkonti/axios-service-base-ts/issues/6) to me

**Comment by Xkonti** [comment]
@corners2wall Ok. `axios-service-base-ts` has been updated to version 0.3.0. You should be able to proceed.
